# Generated by Django 4.0.4 on 2022-05-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_auction_bid_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='foto',
            field=models.FileField(upload_to='images/'),
        ),
    ]
