# Generated by Django 4.0.4 on 2022-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('JWL', 'Jewerly'), ('PNG', 'Painting'), ('SLR', 'Sculpture'), ('TBR', 'Tableware'), ('ACL', 'Alcohol')], max_length=3)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Auction_bid',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
